//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wx
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_chat
    {
        public string Content { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<int> VoiceID { get; set; }
        public int OwnerID { get; set; }
        public long ID { get; set; }
        public string FromUsername { get; set; }
        public long CreateTime { get; set; }
        public int CounterPartyID { get; set; }
        public bool IsFromOwner { get; set; }
    }
}
