//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wx
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_permission
    {
        public long ID { get; set; }
        public int OwnerID { get; set; }
        public int CounterPartyID { get; set; }
        public bool IsPublic { get; set; }
        public string PermittedUserList { get; set; }
        public string SecretWord { get; set; }
    }
}
