//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wx
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_user
    {
        public long Uin { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public string HeadImg { get; set; }
        public bool IsChatroom { get; set; }
        public Nullable<long> ChatroomMasterID { get; set; }
        public int ID { get; set; }
        public string SignalrID { get; set; }
        public string GuidUrl { get; set; }
    }
}
