//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cloudjunsqlEntities : DbContext
    {
        public cloudjunsqlEntities()
            : base("name=cloudjunsqlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<wx_chat> wx_chat { get; set; }
        public DbSet<wx_owner_chat_map> wx_owner_chat_map { get; set; }
        public DbSet<wx_permission> wx_permission { get; set; }
        public DbSet<wx_user> wx_user { get; set; }
    }
}
